apiVersion: v1
kind: Service
metadata:
  name: demo-app1-service
spec:
  type: LoadBalancer
  selector:
    appname: label-app1-acr-image
  ports:
    - protocol: TCP
      port: 9876
      targetPort: 3000
